# Generated by Django 2.2 on 2022-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0003_auto_20220208_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
