# Generated by Django 2.2 on 2022-02-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0004_auto_20220209_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='deafault.png', upload_to=''),
        ),
    ]
