# Generated by Django 2.2 on 2022-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0006_auto_20220209_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('profile_picture', models.ImageField(default='dafault.jpg', null=True, upload_to='')),
                ('bio', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='dafault.jpg', null=True, upload_to=''),
        ),
    ]
