# Generated by Django 2.2 on 2022-02-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0007_auto_20220212_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vibe_App.Post')),
                ('wall_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vibe_App.Wall_Message')),
            ],
        ),
    ]
