# Generated by Django 2.2 on 2022-02-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0008_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vibe_App.Post'),
        ),
        migrations.AlterField(
            model_name='content',
            name='wall_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vibe_App.Wall_Message'),
        ),
    ]
