# Generated by Django 2.2 on 2022-02-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0012_auto_20220225_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album_photo',
            old_name='album_id',
            new_name='album',
        ),
    ]
