# Generated by Django 2.2 on 2022-02-27 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vibe_App', '0013_auto_20220227_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Vibe_App.User'),
            preserve_default=False,
        ),
    ]
